# Generated by Django 4.2.7 on 2025-08-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='discription',
            new_name='description',
        ),
    ]
