# Generated by Django 4.2.7 on 2025-08-09 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
