# Generated by Django 4.2.7 on 2025-08-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_alter_borrowmodel_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='due_date',
            field=models.DateField(),
        ),
    ]
