# Generated by Django 4.2.7 on 2025-08-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_alter_borrowmodel_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
